### ISSUE TITLE
xdebug host config for windows/mac

### ISSUE THREAD

**Issue by JoshuaCarter** [symbiote/docker-project#32]
We should add the following lines to our `xdebug.ini`:

```
xdebug.remote_host=host.docker.internal
xdebug.remote_port=9000
xdebug.idekey=VSCODE
```

This appears to have no impact on xdebug for ubuntu 16.04 (as expected, given the changes).

Alternatively, this can be added to the README for mac/windows users: 
`DOCKER_PHP_COMMAND="docker-php-ext-enable xdebug && echo 'xdebug.remote_host=host.docker.internal' >> /usr/local/etc/php/conf.d/xdebug.ini && echo 'xdebug.remote_port=9000' >> /usr/local/etc/php/conf.d/xdebug.ini && echo 'xdebug.idekey=VSCODE' >> /usr/local/etc/php/conf.d/xdebug.ini && "`

**Comment by Jeremuelle** [comment]
Can we please add those lines on README? Was looking for this for ages. 😅

**Comment by JoshuaCarter** [comment]
PR here: https://github.com/symbiote/docker-project/pull/38

**Comment by nglasl** [comment]
That has since been merged, so closing this :smile:
