### ISSUE TITLE
Bug: Cannot do a command like `yarn remove packagename` without using double quotes like `yarn "remove packagename"`

### ISSUE THREAD

**Issue by silbinarywolf** [symbiote/docker-project#7]
Bug: Cannot do a command like `yarn remove packagename` without using double quotes like:
`yarn "remove packagename"`

**Solutions tried:**
I already tried just wrapping the expanded arguments in quotes but that didn't work. Not that great with Bash though so... yknow.
```
docker exec ${RUN_OPTS} -u `id -u`:`id -g` ${CONTAINER_NAME} bash -c "cd $YARN_DIR; yarn \"$@\""
```

**Comment by nglasl** [comment]
Closing this now that the PR above has been merged.
