### ISSUE TITLE
PHP container needs --enable-sockets (?)

### ISSUE THREAD

**Issue by JoshuaCarter** [symbiote/docker-project#9]
Hit this error on a dropzone.
```
ERROR [User Error]: Uncaught Error: Call to undefined function socket_create() IN POST <path>/Form/field/EditableTextField_4e49d/upload Line 131 in /var/www/html/steamedclams/code/thirdparty/clamd.php 
```

And can't see anywhere that's enabling sockets. Should they be enabled by default?

**Comment by nglasl** [comment]
@symric can you please provide some input here? This doesn't need any work, only a response for now.

**Comment by symric** [comment]
Yeah need to enable in the Dockerfile, using something like:

`docker-php-ext-install sockets`

**Comment by nglasl** [comment]
Going to close this now that a PR exists, in an effort to keep discussions in the one thread https://github.com/symbiote/docker-project/pull/21. Thanks heaps for the PR here!
